name: ${project.name}
version: ${project.version}
author: Haileykins
description: Minecraft Potions at Your Fingertips
main: me.haileykins.PotionsBook.Pbook
depend: [Vault]

commands:
    pbook:
      aliases: [bb, brewbook, potionbook]
      description: Gives You A Brewing Recipe Book